### ISSUE TITLE
Specify expiry date in the appender

### ISSUE THREAD

**Issue by seanfitzg** [log4mongo/log4mongo-net#28]
Hi, I'm wondering if it's possible to set the expiry date of a log record via the appender.  It's simple to do this via:
`db.log_events.createIndex( { "createdAt": 1 }, { expireAfterSeconds: 3600 } )`
...but it'd be nice to be able to do this in the appender.

**Comment by emadb** [comment]
Yep! It's not hard to do, we could add a setting to specify if the user needs the expiry on the collection. The interested code is on [MongoDbAppender (line 90)](https://github.com/log4mongo/log4mongo-net/blob/master/src/Log4Mongo/MongoDBAppender.cs#L90-94).

At the same time we could add something to use the capped collections.

**Comment by emadb** [comment]
We pushed the new version that support the TTL collections.
