### ISSUE TITLE
Source file '..\SharedAssemblyInfo.cs' could not be found

### ISSUE THREAD

**Issue by programmerguru** [log4mongo/log4mongo-net#44]
After downloading source code, when I tried to compile I got this error:

Error	2	Source file '..\SharedAssemblyInfo.cs' could not be found	C:\Users\AbcUs\Documents\GitHub\log4mongo-net\src\Log4Mongo\CSC	Log4Mongo

**Comment by gimmi** [comment]
Run `build.cmd`
