### ISSUE TITLE
Why do you need to ensure the collection exists?

### ISSUE THREAD

**Issue by dschuermans** [log4mongo/log4mongo-net#50]
Hey,

I used log4mongo back when it was still version 0.11.0.0
I recently upgrade to 2.2.0.0 and I noticed it wasn't working for me anymore, due to the fact that my user was unauthorized to run the "listCollections" command.

I have a setup in which I use 1 database to store the logging for several projects (so 1 collection per project)
Each project has it's own mongodb user which is added to the logging database and uses a role defined in the admin database.
When authenticated, these users can insert and query data from collections just fine.
They must however, know the collection name they want to query.
The reason I prevent those users from running "listCollections" is to make sure that nobody can manually authenticate with those logging users and get a list of all logging collections available and potentially viewing logs from another project.

Now as far as I know mongo, you do not need to create a collection beforehand.
If you just type in "db.test.insert({ name: 'joe' })" and the "test" collection doesn't exist, mongo creates it automatically.
So why do you need code which explicitly checks if a collection exists?

Would it be possible to put this part of the code under a feature flag that we can enable or disable ourselves?

**Comment by emadb** [comment]
Hi @dschuermans 
you are right when you sat that mongodb doesn't need to have the collection created beforehand but we need to check because the collection (when requested) must be capped. That's why we need to check if the collection exists.
If you can find a better way to manage the creation of a possibly capped collection please send us a PR. The starting point is here: [MongoDBAppender.cs#L121](https://github.com/log4mongo/log4mongo-net/blob/master/src/Log4Mongo/MongoDBAppender.cs#L121)

**Comment by dschuermans** [comment]
@emadb thanks for your response.

Do you use capped collections only to make sure the database doesn't grow too large?

If so, I achieved the same behavior by using an index on my collection:

use logging;
db.logs.createIndex({ "timestamp": 1}, { expireAfterSeconds: 7776000 });

**Comment by emadb** [comment]
It is an option, even if it is slightly different. The problem I see is that it could slow down the database since every 60 seconds a query is triggered to check what to delete and to delete the expired logs.
Let see what @gimmi and @seanfitzg think.

**Comment by dschuermans** [comment]
@emadb That may be true, but it's an index after all so it shouldn't really matter :)
Now you're pretty much forcing people to use a capped collection? (if the collection doesn't exist)

Isn't it supposed to be up to the user implementing log4mongo to configure their collection properly?
While I agree that it's a good practice to use a capped collection or something that keeps the size of your db in check but I don't think it should be log4mongo's responsibility.
What you can do is provide guidelines or recommendations on how to configure a collection properly for use with log4mongo

On a side note, I can't open the solution.. It complains about the nuget.config file not being correct and the references to log4net and MongoDB are incorrect.
I was thinking about wrapping the collection existance check in a feature flag, so it can be enabled or disabled by the end-user (enabled by default)
