### ISSUE TITLE
No longer maintained ? 

### ISSUE THREAD

**Issue by MohamedChaabouni** [log4mongo/log4mongo-net#52]
Hi =) 

This repo is no longer maintained, can we use it on .Net Core 2.0, 2.1 applications ?

**Comment by gimmi** [comment]
Hi,

well, no one put some effort in maintainig it for a while, and I agree that there are some feature like supporting core that are much needed.

@emadb what's your thought?

**Comment by emadb** [comment]
Hi. 
There are some open issues and the need to support .NET Core. Actually I'm moving away from .NET world so I find difficult find time to make the port.
I could help with PRs if needed.

**Comment by gimmi** [comment]
I'm still doing a fair amount of .NET, so I will se if i have some time to update the project.
