### ISSUE TITLE
Missing support for .net core 2.x

### ISSUE THREAD

**Issue by michalhainc** [log4mongo/log4mongo-net#53]
Any plans for supporting dotnet core?

**Comment by michalhainc** [comment]
aha last commit 2 years ago...

**Comment by michalhainc** [comment]
I rolled my own mongo appender for .net core 2 ... :) not that hard

**Comment by KamranShahid** [comment]
> I rolled my own mongo appender for .net core 2 ... :) not that hard

It would be good if you can upload it on git as well.
What i am thinking is download current classed then compile it on .net core 2.1 (version i am using)  and use it in my application

**Comment by gimmi** [comment]
As a follow-up to this issue, some months ago I've prepared the [v3](https://github.com/log4mongo/log4mongo-net/tree/v3) branch where I've modernized the solution and targeted `netstandard2.0`

I will complete the work when I will have some more time, but in the meantime you can take a look at it

**Comment by KamranShahid** [comment]
I have also took the code and used in my .net core 2.1 library via separate .net core 2.1 library project.
I used mongodbdriver 2.0.8 libraries as referenced. 
I have made some changes in it as well for my custom need like i inherited and implemented BufferingAppenderSkeleton,  ignored loggingEvent.LocationInformation part as we always get ? in those fields, put some checks for BuildExceptionBsonDocument for possible exception source as null and some other code refactoring
